spring:
  jpa:
    properties:
      hibernate:
        format_sql: false

logging:
  structured:
    format:
      console: ecs
  level:
    root: INFO
    com.example.starter: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never
